## 다중 분류에서의 불확실성

In [22]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier
import numpy as np
from sklearn.linear_model import LogisticRegression

In [2]:
iris = load_iris()

In [8]:
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, random_state=0)

In [9]:
gbrt = GradientBoostingClassifier(random_state=0).fit(X_train, y_train)

In [11]:
gbrt.decision_function(X_test)

array([[-4.52759364, -4.85516608,  4.92061892],
       [-4.52669672,  4.97939483, -5.19277184],
       [ 4.80934868, -4.49789689, -5.1552818 ],
       [-4.52529793, -5.21900992,  5.96758268],
       [ 4.80934868, -5.0263473 , -5.1552818 ],
       [-4.52564385, -4.70083878,  5.7147898 ],
       [ 4.80934868, -5.0263473 , -5.1552818 ],
       [-4.52707037,  5.31510258, -3.58061927],
       [-4.52680207,  5.5940426 , -4.77725785],
       [-4.52647447,  5.03715936, -5.19277184],
       [-4.52649821, -2.40587569,  3.74011699],
       [-4.52727463,  5.69828001, -3.86115741],
       [-4.52647447,  4.96911189, -5.19277184],
       [-4.52680207,  4.69046346, -3.48403528],
       [-4.52674277,  4.96911189, -5.19277184],
       [ 4.80934868, -5.0263473 , -5.1552818 ],
       [-4.52674277,  4.63269893, -3.48403528],
       [-4.52697938,  5.08411948, -5.16395818],
       [ 4.80934868, -5.0263473 , -5.1552818 ],
       [ 4.80934868, -5.0263473 , -5.1552818 ],
       [-4.52759364,  0.07366717,  5.569

In [10]:
print("결정 함수의 결과 형태: {}".format(gbrt.decision_function(X_test).shape))

결정 함수의 결과 형태: (38, 3)


In [14]:
print("가장 큰 결정 함수의 인덱스:\n{}".format(np.argmax(gbrt.decision_function(X_test), axis=1)))

가장 큰 결정 함수의 인덱스:
[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [15]:
gbrt.predict(X_test)

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2])

In [16]:
gbrt.predict_proba(X_test)

array([[7.88196528e-05, 5.68030443e-05, 9.99864377e-01],
       [7.43888749e-05, 9.99887396e-01, 3.82151210e-05],
       [9.99862220e-01, 9.07516999e-05, 4.70279586e-05],
       [2.77320382e-05, 1.38581896e-05, 9.99958410e-01],
       [9.99899469e-01, 5.35017329e-05, 4.70297106e-05],
       [3.56950224e-05, 2.99585968e-05, 9.99934346e-01],
       [9.99899469e-01, 5.35017329e-05, 4.70297106e-05],
       [5.31515622e-05, 9.99809901e-01, 1.36947631e-04],
       [4.02292497e-05, 9.99928454e-01, 3.13162948e-05],
       [7.02296381e-05, 9.99893700e-01, 3.60704168e-05],
       [2.56338600e-04, 2.13692198e-03, 9.97606739e-01],
       [3.62286110e-05, 9.99893246e-01, 7.05249385e-05],
       [7.51743742e-05, 9.99886216e-01, 3.86100667e-05],
       [9.92720475e-05, 9.99619088e-01, 2.81640330e-04],
       [7.51542096e-05, 9.99886236e-01, 3.86100675e-05],
       [9.99899469e-01, 5.35017329e-05, 4.70297106e-05],
       [1.05179164e-04, 9.99596439e-01, 2.98381451e-04],
       [6.69743221e-05, 9.99897

In [17]:
print("합:{}".format(np.sum(gbrt.predict_proba(X_test), axis=1)))

합:[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [19]:
print("가장 큰 예측 확률의 인덱스:\n{}".format(np.argmax(gbrt.predict_proba(X_test), axis=1)))

가장 큰 예측 확률의 인덱스:
[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [20]:
gbrt.predict(X_test)

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2])

In [23]:
logreg = LogisticRegression()

In [25]:
named_target = iris.target_names[y_tarin]

In [26]:
logreg.fit(X_train, named_target)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [27]:
print("훈련 데이터에 있는 클래스 종류: {}".format(logreg.classes_))

훈련 데이터에 있는 클래스 종류: ['setosa' 'versicolor' 'virginica']


In [28]:
print("예측: {}".format(logreg.predict(X_test)[:10]))

예측: ['virginica' 'versicolor' 'setosa' 'virginica' 'setosa' 'virginica'
 'setosa' 'versicolor' 'versicolor' 'versicolor']


In [29]:
argmax_dec_func = np.argmax(logreg.decision_function(X_test), axis=1)

In [30]:
print("가장 큰 결정 함수의 인덱스: {}".format(argmax_dec_func[:10]))

가장 큰 결정 함수의 인덱스: [2 1 0 2 0 2 0 1 1 1]


In [31]:
print("인덱스를 classes_에 연결: {}".format(logreg.classes_[argmax_dec_func][:10]))

인덱스를 classes_에 연결: ['virginica' 'versicolor' 'setosa' 'virginica' 'setosa' 'virginica'
 'setosa' 'versicolor' 'versicolor' 'versicolor']
